### ISSUE TITLE
My Gigs : The page must be responsive for tab and mobile views

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#105]
My Gigs : The page must be responsive for tab and mobile views
cc @LieutenantRoger @sushilshinde 
<img width="842" alt="Screenshot 2021-06-08 at 11 50 15 AM" src="https://user-images.githubusercontent.com/58783823/121133681-4544ae80-c850-11eb-92aa-36e4c7c8a556.png">

**Comment by LieutenantRoger** [comment]
Ok, do we need the gig list to support tablet or mobile ?  If so, we might need a design doc firstly.

**Comment by Oanh-and-only-Oanh** [comment]
focus will be on desktop only for now, responsive (Tablet and Mobile) will be for the future iteration
