### ISSUE TITLE
Remarks from RCRM are not displayed, when the user is in open/screen pass status

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#111]
Remarks from RCRM are not displayed, when the user is in open status
example: here the remarks are present in JC record, but not displayed on the FE
<img width="976" alt="Screenshot 2021-06-21 at 12 39 51 PM" src="https://user-images.githubusercontent.com/58783823/122721047-cf980400-d28d-11eb-9eb1-4f7be82ddd2c.png">

<img width="1100" alt="Screenshot 2021-06-21 at 12 38 27 PM" src="https://user-images.githubusercontent.com/58783823/122721040-cd35aa00-d28d-11eb-8753-785d35cf5325.png">

**Comment by LieutenantRoger** [comment]
@SathyaJayabal  Can't reproduce, which API you are visting ?  See what I received from the agg Job API

https://monosnap.com/file/2e7C0pMx78LD3B6SJQEe60hgVcoJZQ

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , please try now for user `topacc_three` for job `REACT DEVELOPER - JOB 1`

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1120" alt="Screenshot 2021-06-22 at 9 40 20 AM" src="https://user-images.githubusercontent.com/58783823/122861918-e433d500-d33d-11eb-8ae5-4b8d8b83cb52.png">

**Comment by SathyaJayabal** [comment]
verified on prod
