### ISSUE TITLE
Handling of progress bar with only one status 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#113]
The statuses (job-closed and rejected-other), can happen at anytime during the application process, hence we cannot predict the progress bar based on current status. How should the progress bar and the status tool tip be displayed for these cases.

At present the show more does not display any additional data. In this case we can  hide the show more link.
The tooltip, has not selected as current status and  job closed as next status. 

<img width="1123" alt="Screenshot 2021-06-21 at 2 19 35 PM" src="https://user-images.githubusercontent.com/58783823/122734757-fb21eb00-d29b-11eb-853f-a09fbf3f7406.png">

**Comment by LieutenantRoger** [comment]
1. We are hidding the progress bar when there's only one status of a job. Do you mean we should hide the 'SHOW MORE' button as well ?   
2. The 'NEXT: XXX' part on the tooltip indicates the job current status.  So if it's wrongly displayed, please tell how to display it.

**Comment by LieutenantRoger** [comment]
![截屏2021-06-22 上午10 10 17](https://user-images.githubusercontent.com/2875203/122851674-f748a400-d341-11eb-9482-b3502dde06c6.png)
Updated it like this for now since it doesn't have progress bar

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , tooltip is good, let's hide the show more too for now as there is no data displayed on show more.

 If needed we can display later.

**Comment by LieutenantRoger** [comment]
Fixed @SathyaJayabal

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , thanks. 
<img width="1101" alt="Screenshot 2021-06-22 at 12 42 54 PM" src="https://user-images.githubusercontent.com/58783823/122880236-6c72a400-d357-11eb-8152-d3d6b25b4beb.png">

**Comment by SathyaJayabal** [comment]
Verified on prod
