### ISSUE TITLE
Profile Update popup: Existing resume not displayed

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#128]
The existing resume must be displayed on the popup like in the design. This also does not allow the user to update any other data without uploading a resume.
<img width="1440" alt="Screenshot 2021-06-24 at 9 38 46 AM" src="https://user-images.githubusercontent.com/58783823/123201515-766be280-d4d0-11eb-89f4-7f0b1fb04b0e.png">
<img width="1440" alt="Screenshot 2021-06-24 at 9 39 02 AM" src="https://user-images.githubusercontent.com/58783823/123201527-7c61c380-d4d0-11eb-8e91-588b6981fb09.png">

**Comment by LieutenantRoger** [comment]
I choose to not display it is to sync the file component behavior from here: https://www.topcoder.com/gigs/26751764/apply, which confirmed by @sushilshinde before.  @SathyaJayabal 

We can add it, for sure, but the fix will require change both the API and Frontend, to make the resume field as an optional one.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , in the gigs apply page too, the existing resume is shown and is used if the user does not upload a new one
<img width="1440" alt="Screenshot 2021-06-24 at 10 41 36 AM" src="https://user-images.githubusercontent.com/58783823/123206153-d4042d00-d4d8-11eb-9456-93fa268cdc1e.png">

**Comment by LieutenantRoger** [comment]
That's outside of the file component, let me know if we follow that part as well, we'll make some adjusments.

**Comment by sushilshinde** [comment]
@LieutenantRoger UI need to show existing resume, same as existing apply form

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , 

1. Can we remove the text "and add them to the tech skills section below." because we dont have the tech skills section here(only on the apply page).

<img width="1440" alt="Screenshot 2021-06-26 at 10 58 01 AM" src="https://user-images.githubusercontent.com/58783823/123502959-8d940700-d66d-11eb-929a-7f879393bfcb.png">

2. We are getting the below error when we update any field (other than the resume) and save. 
<img width="1440" alt="Screenshot 2021-06-26 at 11 00 39 AM" src="https://user-images.githubusercontent.com/58783823/123503032-f7141580-d66d-11eb-92ac-3722c59fc873.png">

**Comment by LieutenantRoger** [comment]
@SathyaJayabal 

1. OK, removed. It is deploying, presumably 5 min later will be ready.

2. This has already been fixed and deployed, please try again.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , Main issue is fixed. Juts  a couple of minor issues.

1. Can we add some padding to the  text here.
<img width="1440" alt="Screenshot 2021-06-26 at 6 23 29 PM" src="https://user-images.githubusercontent.com/58783823/123513599-ae7b4d00-d6ab-11eb-966c-32331ef9da2f.png">

2. Clicking on the resume link must open the resume in new tab like in the gigs  application page. Currently it is opening in the same window

**Comment by SathyaJayabal** [comment]
verified above 2 points
<img width="1440" alt="Screenshot 2021-06-26 at 9 09 42 PM" src="https://user-images.githubusercontent.com/58783823/123518297-eb9f0980-d6c2-11eb-89cb-8811eb54385d.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-29 at 9 38 52 AM" src="https://user-images.githubusercontent.com/58783823/123735992-e0fc9400-d8bd-11eb-98c7-586942adcb77.png">
