### ISSUE TITLE
profile api returns 500 error for users who have not applied to any gigs yet

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#130]
https://platform.topcoder-dev.com/earn-app/api/my-gigs/profile
returns a 500 error for user who have not applied to any gigs yet (no candidate in rcrm yet)
<img width="1440" alt="Screenshot 2021-06-24 at 10 07 31 AM" src="https://user-images.githubusercontent.com/58783823/123203449-04959800-d4d4-11eb-9580-f2de746ad8ef.png">

In these cases, the profile must be loaded with only data from v5/members and on saving new candidate must  be created on RCRM. Is this correct @sushilshinde ?

**Comment by LieutenantRoger** [comment]
Hmmm, our API doesn't support to create RCRM profile yet, can we safely assume that when a member can update profile, he should have profile at RCRM side ?

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , most users may not have applied to a gig yet. what will be the flow for them ?
cc @sushilshinde 

Currently for the gigs application page, when user has not applied before, the candidate is created  in RCRM when they apply for the first time, Can we not use the same feature here ?

**Comment by sushilshinde** [comment]
@LieutenantRoger that button  should disabled for users those don't have records in RCRM
Though I will look for help from Glenn and @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
Correct, please disable update button if user has not applied to any gigs yet

**Comment by crazyk07** [comment]
Correct, disabling is fine.  Also, the only way for someone to know about this page is if they applied for a gig in the first place.

**Comment by SathyaJayabal** [comment]
verified on dev
User without any previous gig application:
<img width="1440" alt="Screenshot 2021-06-25 at 12 40 55 PM" src="https://user-images.githubusercontent.com/58783823/123385047-bc997280-d5b2-11eb-855b-e2b47a28b116.png">
user with gig applications
<img width="1440" alt="Screenshot 2021-06-25 at 12 41 21 PM" src="https://user-images.githubusercontent.com/58783823/123385087-c622da80-d5b2-11eb-9ab5-0abbd70ad0bb.png">

**Comment by SathyaJayabal** [comment]
verified on prod.
