### ISSUE TITLE
Unable to update city 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#131]
When updating the profile, we get the error, `"createdBy" must be a string `
<img width="1440" alt="Screenshot 2021-06-24 at 10 37 13 AM" src="https://user-images.githubusercontent.com/58783823/123205892-4d4f5000-d4d8-11eb-9e0f-5fa6e4b90eab.png">

**Comment by LieutenantRoger** [comment]
Could you try Incognito mode, it looks fine when I update: https://monosnap.com/file/jRuZcbW9gWAbcKzLeM3kz23Fj3tDzu

**Comment by SathyaJayabal** [comment]
for the `topacc_three` user I get the following error
<img width="1440" alt="Screenshot 2021-06-24 at 11 01 11 AM" src="https://user-images.githubusercontent.com/58783823/123207848-a7054980-d4db-11eb-890e-3bb6a0ba1718.png">

**Comment by sushilshinde** [comment]
@LieutenantRoger is that the same user account that got corrupted data while development?

**Comment by LieutenantRoger** [comment]
We should not have corrupted data any more.  let me try to reproduce this

**Comment by SathyaJayabal** [comment]
@LieutenantRoger @sushilshinde , this is not due to corrupted data, Its because the user has not  added an address to their member profile yet. When we try to write only the  city, we get this error. This is validation on the members api side for updating address.

**Comment by LieutenantRoger** [comment]
Hmmm, but if we are trying to add a new city for a member only, what to fill the addr1 ? We don't have UI to accept the params, shall I pass just empty for them ?

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , but I am able to change only city form member profile. So not sure why we get this error.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , now we get the following error when updating city for users who dont have an address yet

Note: before it was `streetAddr1` now it is `streetAddr2`

<img width="1440" alt="Screenshot 2021-06-25 at 12 55 24 PM" src="https://user-images.githubusercontent.com/58783823/123386761-a1c7fd80-d5b4-11eb-83b5-54f57143afe4.png">

**Comment by LieutenantRoger** [comment]
Ok, hmmm, looks similar issue. Let me add default value for streetAddr2.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger Also when address details are already present and user tries to update city, we get the following error

<img width="1440" alt="Screenshot 2021-06-25 at 2 13 38 PM" src="https://user-images.githubusercontent.com/58783823/123397108-afcf4b80-d5bf-11eb-92d8-dd9552d967a2.png">
<img width="1440" alt="Screenshot 2021-06-25 at 2 13 48 PM" src="https://user-images.githubusercontent.com/58783823/123397157-bb227700-d5bf-11eb-8edc-d1cd63397593.png">

**Comment by LieutenantRoger** [comment]
I have specified the default value for streetAddr2, and deleted createdBy and  updatedBy

**Comment by SathyaJayabal** [comment]
@LieutenantRoger

1. Case where address is already added, City is getting updated correctly. But we get the following error from api and the successful message is not shown.
<img width="1440" alt="Screenshot 2021-06-26 at 11 42 43 AM" src="https://user-images.githubusercontent.com/58783823/123503944-c0d99480-d673-11eb-8a11-52b3c48b4916.png">

**Comment by LieutenantRoger** [comment]
Please try again

**Comment by SathyaJayabal** [comment]
Case 1 : Address already added in member profile. The city gets updated from the my gigs popup as expected.
Case 2: Address not present in member profile. The city gets updated from my gigs popup as expected. The address 1, address 2, state and zip fields are updated with space. This is to overcome the situation where we are only adding the city and other fields are expected to be not null. cc @sushilshinde @Oanh-and-only-Oanh 
before update
<img width="1440" alt="Screenshot 2021-06-26 at 2 21 54 PM" src="https://user-images.githubusercontent.com/58783823/123507952-36e8f600-d68a-11eb-87e4-c05d3b86ced9.png">
after update
<img width="1440" alt="Screenshot 2021-06-26 at 2 25 13 PM" src="https://user-images.githubusercontent.com/58783823/123508008-7c0d2800-d68a-11eb-9ea2-7043ce54314c.png">

**Comment by SathyaJayabal** [comment]
verified on prod
