### ISSUE TITLE
Profile Update: City and Country details are not getting updated to RCRM 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#132]
Profile Update: City and Country details are not getting updated to RCRM 

<img width="1440" alt="Screenshot 2021-06-24 at 2 49 15 PM" src="https://user-images.githubusercontent.com/58783823/123237801-9bc21600-d4fb-11eb-9121-f8542f2c62c8.png">
<img width="1440" alt="Screenshot 2021-06-24 at 2 49 31 PM" src="https://user-images.githubusercontent.com/58783823/123237832-a11f6080-d4fb-11eb-8c35-beb7a9696bc9.png">
<img width="1217" alt="Screenshot 2021-06-24 at 2 49 53 PM" src="https://user-images.githubusercontent.com/58783823/123237838-a2508d80-d4fb-11eb-8ca8-708a531de33f.png">

**Comment by sushilshinde** [comment]
yeah that's a bug

**Comment by SathyaJayabal** [comment]
verified on dev, city and country updated to RCRM city and location
<img width="1440" alt="Screenshot 2021-06-26 at 2 17 26 PM" src="https://user-images.githubusercontent.com/58783823/123508057-ba0a4c00-d68a-11eb-9fa4-cc4b83f0bca3.png">
<img width="1440" alt="Screenshot 2021-06-26 at 2 17 39 PM" src="https://user-images.githubusercontent.com/58783823/123508063-c0002d00-d68a-11eb-9455-ea7c3c38420c.png">

**Comment by SathyaJayabal** [comment]
verified  on prod
