### ISSUE TITLE
Profile Update: v5 member traits Country field must also be updated

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#133]
during profile update, v5 member traits Country field must also be updated

example: 
1. Go to member profile settings and check country :
home country code, competition country code and country  are all Japan
<img width="1440" alt="Screenshot 2021-06-24 at 2 59 24 PM" src="https://user-images.githubusercontent.com/58783823/123239331-e2fcd680-d4fc-11eb-904f-c87a67d5e20e.png">

2. Go to update gig work profile. country is Japan as expected. 
<img width="1440" alt="Screenshot 2021-06-24 at 3 02 22 PM" src="https://user-images.githubusercontent.com/58783823/123239694-41c25000-d4fd-11eb-8a33-e65e63e37d30.png">

3. Update country to China
<img width="1440" alt="Screenshot 2021-06-24 at 3 03 23 PM" src="https://user-images.githubusercontent.com/58783823/123239795-57d01080-d4fd-11eb-819a-6346ba2938a2.png">

4. Check member profile, country not updated to china (even though home country code, competition country code is updated)

<img width="1440" alt="Screenshot 2021-06-24 at 3 04 29 PM" src="https://user-images.githubusercontent.com/58783823/123240044-95cd3480-d4fd-11eb-8259-9ab8f50aef2b.png">

**Comment by sushilshinde** [comment]
That observation is right 

@Oanh-and-only-Oanh please suggest

**Comment by LieutenantRoger** [comment]
We have added logic to update members’ trait info.

**Comment by SathyaJayabal** [comment]
verified on dev:
1. country updated from gigs profile update is reflected on member profile
<img width="1440" alt="Screenshot 2021-06-25 at 1 34 41 PM" src="https://user-images.githubusercontent.com/58783823/123392072-4862cd00-d5ba-11eb-96f9-4bd255d4394e.png">
<img width="1440" alt="Screenshot 2021-06-25 at 1 34 45 PM" src="https://user-images.githubusercontent.com/58783823/123392102-4d278100-d5ba-11eb-8b7e-db88b1d5a2c1.png">

2. country updated in member profile, is loaded in gigs profile update
<img width="1440" alt="Screenshot 2021-06-25 at 1 37 32 PM" src="https://user-images.githubusercontent.com/58783823/123392462-b3ac9f00-d5ba-11eb-9a59-d404fa2cd5b6.png">
<img width="1440" alt="Screenshot 2021-06-25 at 1 37 08 PM" src="https://user-images.githubusercontent.com/58783823/123392439-adb6be00-d5ba-11eb-8191-0599ad093135.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-29 at 9 34 10 AM" src="https://user-images.githubusercontent.com/58783823/123735657-3be1bb80-d8bd-11eb-8316-c2dae8b955c0.png">
<img width="1440" alt="Screenshot 2021-06-29 at 9 34 32 AM" src="https://user-images.githubusercontent.com/58783823/123735671-41d79c80-d8bd-11eb-9416-533d638d1cc4.png">
