### ISSUE TITLE
Profile update: Blank page on selecting some countries 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#136]
Getting this error when `United States Minor Outlying Island` is selected from the country dropdown. 

<img width="1440" alt="Screenshot 2021-06-25 at 1 02 08 PM" src="https://user-images.githubusercontent.com/58783823/123387644-a17c3200-d5b5-11eb-8e44-e12e9fb6e96c.png">

https://user-images.githubusercontent.com/58783823/123387602-97f2ca00-d5b5-11eb-8455-17cada1d126d.mov

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , this is now happening to all countries. 

https://user-images.githubusercontent.com/58783823/123504292-e5cf0700-d675-11eb-8721-7ddee59abd8e.mov

**Comment by LieutenantRoger** [comment]
We used this library for verifying the country code of a phone number `country-calling-code`

The country selected can't be find in the library `country-calling-code`,  the current strategy is disabling country code validation if user selected one country which doesn exist in this library `country-calling-code`

@SathyaJayabal @sushilshinde  

Please let me know if this way works.

**Comment by SathyaJayabal** [comment]
Verified. If the country is not in the list then validation does not happen. There is no blank page error.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-29 at 9 28 43 AM" src="https://user-images.githubusercontent.com/58783823/123735211-6bdc8f00-d8bc-11eb-8a16-0d441ffeb15a.png">
