### ISSUE TITLE
Profile update: Country is not updated in member profile for new user with no basic info added yet

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#137]
Profile update: Country is not updated in member profile for new user with no basic info added yet

example: tester123456
1. open update profile popup from my gigs page. City and country are empty.
https://platform.topcoder-dev.com/earn/my-gigs
<img width="1440" alt="Screenshot 2021-06-25 at 1 44 24 PM" src="https://user-images.githubusercontent.com/58783823/123404717-c0cf8b00-d5c6-11eb-9202-9f09b04c1001.png">
2. Update country and save 
3. Access member profile
https://www.topcoder-dev.com/settings/profile
Updated country not reflecting. This is because the basic_info traits has not yet been created for the user in v5,
<img width="1440" alt="Screenshot 2021-06-25 at 1 50 03 PM" src="https://user-images.githubusercontent.com/58783823/123404962-00967280-d5c7-11eb-87c3-4209d419d2e3.png">

**Comment by LieutenantRoger** [comment]
Current earn-app will update member basic traits data when the member has traits, the above scenario is when member doesn't have basic traits info. 

Please let me know whether we need to create traits on earn-app when member updated his profile.

This will involve to integrate another traits API I think.  

@sushilshinde @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
This should be  fixed if this issue on community app is fixed
https://github.com/topcoder-platform/community-app/issues/5501

cc @sushilshinde

**Comment by SathyaJayabal** [comment]
fixed in https://github.com/topcoder-platform/community-app/issues/5501
