### ISSUE TITLE
Getting a blank page on clicking "Update Gig Work Profile" button

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#138]
Getting a blank page on clicking "Update Gig Work Profile" button, after the user has updated their profile once.

<img width="1440" alt="Screenshot 2021-06-26 at 11 11 39 AM" src="https://user-images.githubusercontent.com/58783823/123503238-4c9cf200-d66f-11eb-84b3-24359797d94d.png">

https://user-images.githubusercontent.com/58783823/123503232-427af380-d66f-11eb-9b4a-d092dae0853e.mov

**Comment by SathyaJayabal** [comment]
Additional info: The country value is not getting updated correctly when we save any updates.
<img width="1440" alt="Screenshot 2021-06-26 at 11 24 56 AM" src="https://user-images.githubusercontent.com/58783823/123503545-3859f480-d671-11eb-9868-dc596231d1dd.png">

**Comment by LieutenantRoger** [comment]
> Additional info: The country value is not getting updated correctly when we save any updates.
> <img alt="Screenshot 2021-06-26 at 11 24 56 AM" width="1440" src="https://user-images.githubusercontent.com/58783823/123503545-3859f480-d671-11eb-9868-dc596231d1dd.png">

This user seems having currpted data, the competitionCountryCode should not be "undefined",  it may caused by previous API change.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , its getting set to undefined when we update from the popup.

**Comment by SathyaJayabal** [comment]
This is fixed and verified on dev

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-29 at 9 27 38 AM" src="https://user-images.githubusercontent.com/58783823/123735126-45b6ef00-d8bc-11eb-8ec8-2be5bf8a027b.png">
