### ISSUE TITLE
Direct "Feedback" to forums not github

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-earn-app#144]
### Current behavior
When user clicks on "give feedback" button, user is direct to Github to open a ticket.

### Expected behavior
When user clicks on "give feedback" button, user should be directed to Forums https://discussions.topcoder.com/discussion/8870/new-beta-site-discuss?new=1.

1) 
![image](https://user-images.githubusercontent.com/47536078/124015755-d6afc800-d999-11eb-9b82-f03aa91b6160.png)
2) 
![image](https://user-images.githubusercontent.com/47536078/124015830-e3342080-d999-11eb-936a-e1b524302698.png)
3) Update Banner to "WELCOME TO OUR BETA WORK LISTINGS SITE - TELL US WHAT YOU THINK!

Welcome to the Beta version of the new Challenge Listings. During this Beta phase, we will be fine-tuning the platform based on feedback we receive from you, our community members.

NOTE THAT THIS IS NOT THE FINAL VERSION OF THE SITE.
You may encounter occasional broken links or error messages. If so, please let us know! This is what the Beta phase is intended for, and your feedback will enable us to greatly improve the new site.

You can click on the Feedback button on page or post a comment on Forums at https://discussions.topcoder.com/discussion/8870/new-beta-site-discuss?new=1.
Thank you!

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh  @sushilshinde @urwithat 

This should be fixed. Here's the PR to dev: 
https://github.com/topcoder-platform/micro-frontends-earn-app/pull/146 

![Screen Shot 2021-07-02 at 14 21 46](https://user-images.githubusercontent.com/4476442/124236893-267cc380-db41-11eb-8cfc-8942df715a1b.png)
![Screen Shot 2021-07-02 at 14 21 54](https://user-images.githubusercontent.com/4476442/124236898-28468700-db41-11eb-9338-bcb3d0779bcc.png)

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , I think we should change the text here. It mentions file a github ticket.
<img width="1109" alt="Screenshot 2021-07-07 at 8 46 10 AM" src="https://user-images.githubusercontent.com/58783823/124694954-dd8d8c00-deff-11eb-9060-3b382b30aee9.png">

**Comment by sushilshinde** [comment]
@dedywahyudi comment out this part `or file a github ticket at https://discussions.topcoder.com/discussion/8870/new-beta-site-discuss?new=1.` for now as we are going live today. Whenever we have a new text, later we can change it. PR asap.

**Comment by dedywahyudi** [comment]
@sushilshinde Ok, i'm working on it

**Comment by dedywahyudi** [comment]
@sushilshinde @LieutenantRoger 

Please check the fix on this PR: https://github.com/topcoder-platform/micro-frontends-earn-app/pull/152

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-07-07 at 11 48 10 AM" src="https://user-images.githubusercontent.com/58783823/124709640-55b47b80-df19-11eb-8b20-dcf7e16f7f4c.png">
<img width="1440" alt="Screenshot 2021-07-07 at 11 48 13 AM" src="https://user-images.githubusercontent.com/58783823/124709655-5baa5c80-df19-11eb-9685-9e3d5ccdb681.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-07-07 at 4 54 54 PM" src="https://user-images.githubusercontent.com/58783823/124751339-2109e980-df44-11eb-9692-8e1bd4033e32.png">
<img width="1440" alt="Screenshot 2021-07-07 at 4 54 41 PM" src="https://user-images.githubusercontent.com/58783823/124751380-3121c900-df44-11eb-8156-3d6e4152c079.png">

**Comment by Oanh-and-only-Oanh** [comment]
looks fine. thanks all.
