### ISSUE TITLE
Return to gigs listing : Flow continuity 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/micro-frontends-earn-app#145]
When a user lands on My Gigs(Earn) from Gigs listing(Community App), they do not have navigation back to gigs listing. Need a design to add user experience.

**Comment by Oanh-and-only-Oanh** [comment]
Design for a button/link to allow users to navigate from My Gigs on Earn back to the gigs listings page on Community App? A button/link on this page should direct user to https://www.topcoder.com/gigs
![image](https://user-images.githubusercontent.com/47536078/124163631-9a8d6d80-da54-11eb-96d5-bcf50958628a.png)


1) If user does not have any open Gig applications,  add CTA link/button to middle of page to direct to gigs listings page. "View available Gig opportunities". 
2) All users (logged-in/out, with and without submitted applications), should see a button next to "update profile" button called "View available Gig opportunities"

**Comment by LieutenantRoger** [comment]
@Oanh-and-only-Oanh 

1. I think this will require a design input.  @Dara K.

2. I added a button like this https://monosnap.com/file/V1D4xuNdrF6CIpf684kRsXUnNMIa2J  based on the design from here, let me know if I shall change the button text:  https://marvelapp.com/prototype/cd37c0d/screen/80658602
(Here's the discussion link in the slack channel about this:  https://topcoder.slack.com/archives/C020Y9C74G6/p1625404144142700?thread_ts=1625139939.091700&cid=C020Y9C74G6 )

**Comment by fajarmln** [comment]
Let me know if it needs any design updates @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
Looks fine. Let's proceed.

**Comment by SathyaJayabal** [comment]
verified on dev @LieutenantRoger 
<img width="1440" alt="Screenshot 2021-07-07 at 8 43 13 AM" src="https://user-images.githubusercontent.com/58783823/124694704-6eb03300-deff-11eb-9d1a-a76e363778a1.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-07-07 at 4 53 32 PM" src="https://user-images.githubusercontent.com/58783823/124751119-e607b600-df43-11eb-9598-6236ab2e96e7.png">
