### ISSUE TITLE
View job description of applied to gig

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-earn-app#147]
**Current behavior**
Currently, when the user has applied to a gig and that gig application is pending under MY GIG page, there is no way for the user to review that particular job description again.

**Expected behavior**
When the user has applied to a gig and that gig application is pending under MY GIG page, user can view the job description of the job they applied to if they click on the job title.

![image](https://user-images.githubusercontent.com/47536078/124301833-3a123500-db15-11eb-9e5d-79ce75d137d3.png)

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh 

How user start apply the Gig? I'm not see the Gig list: https://platform.topcoder-dev.com/earn/my-gigs
Using TonyJ account.

**Comment by Oanh-and-only-Oanh** [comment]
The user has to submit a gig application

**Comment by dedywahyudi** [comment]
![Screen Shot 2021-07-04 at 10 05 53](https://user-images.githubusercontent.com/4476442/124371793-7a0d1f80-dcaf-11eb-9487-13fc445f43c9.png)

This is what i see now.

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@dedywahyudi , you can use user topacc_three, I willl message you the password.

**Comment by dedywahyudi** [comment]
@SathyaJayabal Cool, thanks!

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh @SathyaJayabal 

- When user click the title just need linking to the Gig page? 
- It look we need update the API first, there's no url data on the response

![Screen Shot 2021-07-07 at 13 16 49](https://user-images.githubusercontent.com/4476442/124709483-bcd82d00-df25-11eb-9221-3cf48e0756ec.png)

**Comment by Oanh-and-only-Oanh** [comment]
yes, when user clicks the title of the job, it should take them to the job description. Can you work with @sushil if API needs updating?

**Comment by dedywahyudi** [comment]
@sushilshinde @Oanh-and-only-Oanh 

Okay, pls let me know if API updated. 
I'll fix the frontend accordiingly.

**Comment by Oanh-and-only-Oanh** [comment]
@dedywahyudi, which api needs updating here?

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh @SathyaJayabal 

The endpoint should be: https://platform.topcoder-dev.com/earn-app/api/my-gigs/myJobApplications?status=open_jobs&page=2&perPage=10

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , should clicking on the title take the user to the Gigs details page on community app?

**Comment by Oanh-and-only-Oanh** [comment]
correct, @SathyaJayabal

**Comment by SathyaJayabal** [comment]
Ok, so the gig detail url will be like
`https://www.topcoder.com/gigs/28596760`
We need the `28596760`, which is the  external id in the job record, to be included in the api response.

cc @LieutenantRoger , need to add jobExternalId field in the response object of https://platform.topcoder-dev.com/earn-app/api/my-gigs/myJobApplications. This will be constructed from `externalId` field in the job record.

**Comment by LieutenantRoger** [comment]
Added jobExternalId like this:

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , looks good. @dedywahyudi, please check and let us know if you are good on the api changes?

**Comment by dedywahyudi** [comment]
@LieutenantRoger @SathyaJayabal 

Great, thanks. I'll let you know once the update ready.

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh @SathyaJayabal @LieutenantRoger 

PR for this ready: https://github.com/topcoder-platform/micro-frontends-earn-app/pull/161

Link added to the detail, screenshot attached: 
![Screen Shot 2021-07-21 at 12 40 07](https://user-images.githubusercontent.com/4476442/126436956-bd008686-42c8-48ec-b2e6-2e9e8980dd55.png)

**Comment by LieutenantRoger** [comment]
OK, thanks @dedywahyudi  

let me merge it firstly and deploy to dev environment so @SathyaJayabal  could take a look.

**Comment by SathyaJayabal** [comment]
verified on dev, title linking to comm app job details page for all buckets
<img width="1440" alt="Screenshot 2021-07-23 at 12 28 56 PM" src="https://user-images.githubusercontent.com/58783823/126747535-02882b28-0c0b-4cfa-a57b-b531a9435708.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-07-26 at 1 11 27 PM" src="https://user-images.githubusercontent.com/58783823/126951580-838be7c0-2b3f-4e11-af88-f5a77ef339ab.png">
