### ISSUE TITLE
My gigs page not working

### ISSUE THREAD

**Issue by Abhi8909** [topcoder-platform/micro-frontends-earn-app#156]
### Expected behavior
https://platform.topcoder.com/earn/my-gigs - The page should show my gigs' information.

### Actual behavior
But the page is not showing anything in XHR I show the status API is failing.

### Steps to reproduce the problem
Just login to topcoder and click on this link https://platform.topcoder.com/earn/my-gigs

### Screenshot/screencast
<img width="1440" alt="Screenshot 2021-07-08 at 10 17 49 PM" src="https://user-images.githubusercontent.com/21118473/124960820-5db80c80-e03a-11eb-8771-403a6b2246fb.png">

--

#### Environment
- OS:  Mac
- Browser (w/version): Brave Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64)
- User role (client, copilot or manager): Client
- Account userd: abhi2304

**Comment by LieutenantRoger** [comment]
Hey @Abhi8909  Thanks for reporting, 

it seems working on my side, can you show the console tab and try to let us know what 13 errors you are having please ? 

![image](https://user-images.githubusercontent.com/2875203/124961881-9236c300-e050-11eb-9716-1855412ba096.png)

**Comment by Abhi8909** [comment]
Hi Topcoder-Platform/Micro-Frontends-Earn-App

I have attached the screenshot of the console. PFA

**Comment by LieutenantRoger** [comment]
@Abhi8909 By console, I mean this tab from your snapshot, as you can see the console tab is reporting 13 errors.: https://monosnap.com/file/8RUOfeR3KPPENnFyyDkGkhXYw5JU9T

2.  BTW, I have installed `Brave browser` and tried the my-gigs app, it works on my side using Brave.  So I suggest to switch your network or switch to chrome browser to try the app, and see if the issue is resolved.

**Comment by SathyaJayabal** [comment]
@Abhi8909 , do you still face the problem?

**Comment by Abhi8909** [comment]
No, it is working fine now.

**Comment by SathyaJayabal** [comment]
Thanks @Abhi8909
