### ISSUE TITLE
My Gigs 1.5

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#157]
- [x] Add the below filters to the My Gigs Listings:

- Open Applications : This bucket will include all applications in the following statuses
Applied, Skills Test, Phone Screen, Screen Pass, Interview Pass, Selected, Offered, Placed (future and ongoing)
- Completed Gigs : This bucket will include all placed jobs that are completed. Define new FE status Completed
- Archived Applications : This bucket will include all applications with the following statuses  
Job Closed, Not Selected, Withdrew 

- [x] Add Nav item "Gigs" under Find Work, and link it to `https://www.topcoder.com/gigs`

- [x] Add new bucket "Active Gigs" for currently placed applications
- [x] Update Job cards based on new design
https://marvelapp.com/prototype/157fa1ie/screen/80979860

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , pending:
open applications must not have completed jobs
archived applications: withdrew jobs should have withdrew status

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , verified cases where there are no gigs to display
<img width="1440" alt="Screenshot 2021-07-23 at 9 52 25 AM" src="https://user-images.githubusercontent.com/58783823/126737151-c839223c-b1a0-4182-a601-6b3fb072e44a.png">
<img width="1440" alt="Screenshot 2021-07-23 at 9 52 32 AM" src="https://user-images.githubusercontent.com/58783823/126737160-f2c816cb-2bd7-4d5b-a919-03ed96115a7e.png">
<img width="1440" alt="Screenshot 2021-07-23 at 9 52 39 AM" src="https://user-images.githubusercontent.com/58783823/126737163-9bca9260-b96f-48f7-9410-b33748c470ca.png">
<img width="1440" alt="Screenshot 2021-07-23 at 9 52 42 AM" src="https://user-images.githubusercontent.com/58783823/126737167-5060f102-6e02-450d-ac0d-5a06e3d1d6aa.png">

Note: The height of the white box is smaller for the active, completed and archived buckets when compared to the open bucket
<img width="1440" alt="Screenshot 2021-07-23 at 9 55 22 AM" src="https://user-images.githubusercontent.com/58783823/126737301-471f584f-c993-4fd9-9df6-331309c6b306.png">

**Comment by LieutenantRoger** [comment]
@SathyaJayabal  The height of the four buckets have been aligned with `Open Application` bucket when showing empty information.

**Comment by SathyaJayabal** [comment]
Verified on Dev
<img width="1440" alt="Screenshot 2021-08-02 at 11 28 02 AM" src="https://user-images.githubusercontent.com/58783823/127811174-67da7b3a-c2a3-495d-9aa0-11d24047a889.png">
<img width="1440" alt="Screenshot 2021-08-02 at 11 28 05 AM" src="https://user-images.githubusercontent.com/58783823/127811186-d6d0dc5f-8aef-433a-aa1a-5481aef736a6.png">
<img width="1440" alt="Screenshot 2021-08-02 at 11 28 09 AM" src="https://user-images.githubusercontent.com/58783823/127811193-9cebd548-49a3-4ed3-b5c6-182088ef936c.png">
<img width="1440" alt="Screenshot 2021-08-02 at 11 28 12 AM" src="https://user-images.githubusercontent.com/58783823/127811195-c82da352-7159-4663-a9b3-fd74db1aca1c.png">

**Comment by SathyaJayabal** [comment]
verified on prod.

https://user-images.githubusercontent.com/58783823/128870647-ba326384-0d51-4529-9953-e07a0724bb60.mov
