### ISSUE TITLE
Zap System Update Requirement : My Gigs 1.5 Auto Withdraw feature

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-earn-app#160]
Requirement: 

We are adding two new status in JobCandidate `withdrawn`, `withdrawn-prescreen`, and a jobCandidate might be changed into one of these status based on some business logic check. 

Expect: 

Update the Zap system, so that once a job candidate is changed into 'withdrawn' or 'withdrawn-prescreen` in taas system, it can sync with RCRM system with the new status there.

The new status on RCRM system is `Member- Withdrawn`

**Comment by SathyaJayabal** [comment]
verified on dev

**Comment by SathyaJayabal** [comment]
verified on prod
