### ISSUE TITLE
Update the Earn-App browser title

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-earn-app#175]
Update the browser's title into `Listings-EARN-Topcoder`, so when member opens up Earn App, the browser title should become `Listings-EARN-Topcoder`

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-08-17 at 8 35 14 AM" src="https://user-images.githubusercontent.com/58783823/129657427-4b26c1f5-eb12-494f-b2f6-24f15653b70a.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-08-17 at 10 36 55 AM" src="https://user-images.githubusercontent.com/58783823/129666942-e76b7ce8-f273-492d-9ed1-8cfc29241933.png">
