### ISSUE TITLE
Earn App Restructure

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#179]
https://www.topcoder.com/challenges/d8baa61a-4f17-4cb8-bb93-5159c16dd116

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. All the Earns app functionality are working fine.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-09-13 at 8 41 23 PM" src="https://user-images.githubusercontent.com/58783823/133110338-ee373f63-06e9-4b2d-a5c1-9c0874fa5adb.png">
<img width="1440" alt="Screenshot 2021-09-13 at 8 41 04 PM" src="https://user-images.githubusercontent.com/58783823/133110373-f5ac1bd7-6465-4ae3-9ef2-e5db28242eb2.png">
