### ISSUE TITLE
Prod config not picking up

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/micro-frontends-earn-app#34]
Build is taking up only default config 

and prod
https://github.com/topcoder-platform/micro-frontends-earn-app/blob/c07b138b700c312c65e52889b2cad2ed62c1bc38/config/production.js

**Comment by SathyaJayabal** [comment]
This is working now
<img width="1440" alt="Screenshot 2021-04-07 at 5 00 54 PM" src="https://user-images.githubusercontent.com/58783823/113859713-d94bb880-97c2-11eb-86f4-ae58a9da3a8f.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @sushilshinde , now dev has prod api calls
<img width="1440" alt="Screenshot 2021-04-13 at 2 37 44 PM" src="https://user-images.githubusercontent.com/58783823/114527617-d428b680-9c65-11eb-8b89-9dd8e330782a.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This was fixed.

**Comment by SathyaJayabal** [comment]
Verified
Dev env loads dev challenges and prod env loads prod challenges
<img width="1440" alt="Screenshot 2021-04-21 at 5 02 08 PM" src="https://user-images.githubusercontent.com/58783823/115547043-6ca4e380-a2c3-11eb-835c-8c12e0adad79.png">
<img width="1440" alt="Screenshot 2021-04-21 at 5 02 11 PM" src="https://user-images.githubusercontent.com/58783823/115547074-762e4b80-a2c3-11eb-8c7d-8e15e3c40db5.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod . Challenges are displayed correctly according to the Env

![image](https://user-images.githubusercontent.com/55895538/115652362-1342c000-a368-11eb-956c-b7146fcb41a5.png)
![image](https://user-images.githubusercontent.com/55895538/115652388-205faf00-a368-11eb-92e6-9acc53d3bb10.png)

**Comment by sushilshinde** [comment]
@luizrrodrigues why you did open this issue again?
