### ISSUE TITLE
[$80] URLs are not updating based on filtering settings

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-earn-app#48]
****Describe issue:**
The URL is not updating when search/filtering perimeters are set

**How to reproduce:**
1. enter any search word in search bar
2. URL does not change

1. select "closed challenges" on fliter
2. URL does not change

**Expected behavior:****
The URL should change based on sorting/filtering/searching perimeters

**Comment by sandhiyakavi** [comment]
URLs are updating based on  the filter settings now

If filtered by track, Dev

https://platform.topcoder.com/earn/find/challenges?bucket=Open%20for%20Registration&page=1&perPage=10&recommended=true&sortBy=bestMatch&totalPrizesFrom=0&totalPrizesTo=10000&tracks[]=DEV&types[]=CH&types[]=F2F&types[]=TSK

If filtered by Challenge type: F2F

https://platform.topcoder.com/earn/find/challenges?bucket=Open%20for%20Registration&page=1&perPage=10&recommended=true&sortBy=bestMatch&totalPrizesFrom=0&totalPrizesTo=10000&tracks[]=DEV&types[]=F2F

If filtered by Skills/Technology: Unity3D
https://platform.topcoder.com/earn/find/challenges?bucket=Open%20for%20Registration&includeAllTags=true&page=1&perPage=10&recommended=true&sortBy=bestMatch&tags[]=Unity3D&totalPrizesFrom=0&totalPrizesTo=10000&tracks[]=DEV&types[]=F2F

If filtered by Prize amount
https://platform.topcoder.com/earn/find/challenges?bucket=Open%20for%20Registration&page=1&perPage=10&recommended=true&sortBy=bestMatch&totalPrizesFrom=500&totalPrizesTo=1000&tracks[]=DEV&types[]=F2F

If recommended challenges toggled off
https://platform.topcoder.com/earn/find/challenges?bucket=Open%20for%20Registration&page=1&perPage=10&recommended=false&sortBy=updated&totalPrizesFrom=500&totalPrizesTo=1000&tracks[]=DEV&types[]=F2F

If searched for a text (Taas) and sorted by Most recent

https://platform.topcoder.com/earn/find/challenges?bucket=Open%20for%20Registration&page=1&perPage=10&recommended=true&search=Taas&sortBy=updated&totalPrizesFrom=0&totalPrizesTo=10000&tracks[]=DES&tracks[]=DEV&tracks[]=DS&types[]=CH&types[]=F2F&types[]=TSK

**Comment by luizrrodrigues** [comment]
@SathyaJayabal we good to close this one.
