### ISSUE TITLE
Open for registration count varies compared to current challenge count

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-earn-app#57]
Description:

Open for registration count varies compared to current challenge count

![image](https://user-images.githubusercontent.com/55895538/114657733-a5751380-9d2b-11eb-8f9a-9facba9d96c3.png)

![image](https://user-images.githubusercontent.com/55895538/114657775-b32a9900-9d2b-11eb-9519-5ca961c33a58.png)

**Comment by sandhiyakavi** [comment]
The two Data science challenges are not displayed in Earns app

![image](https://user-images.githubusercontent.com/55895538/114660323-14ed0200-9d30-11eb-9db1-7c60612f5c67.png)

**Comment by SathyaJayabal** [comment]
@sandhiyakavi , can u reverify this issue please? This could be because of the prize amount filter default values.

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. The counts are correctly displaying now

<img width="960" alt="earnapp_openforreg" src="https://user-images.githubusercontent.com/55895538/115812179-eb1c9500-a42b-11eb-8de4-e4314389bdb8.png">
<img width="959" alt="community_openforreg" src="https://user-images.githubusercontent.com/55895538/115812187-eeb01c00-a42b-11eb-9933-4939d82f54c0.png">
