### ISSUE TITLE
[$20] Open for registration count is missing

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-earn-app#6]
Open for registration count is missing
<img width="1440" alt="Screenshot 2021-04-02 at 5 58 32 PM" src="https://user-images.githubusercontent.com/58783823/113415567-21429800-93dd-11eb-9c43-21cc7e1b455e.png">
<img width="1440" alt="Screenshot 2021-04-02 at 5 58 50 PM" src="https://user-images.githubusercontent.com/58783823/113415597-2b649680-93dd-11eb-923e-90698758d038.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , this seems to be fixed in the second challenge
<img width="1440" alt="Screenshot 2021-04-13 at 5 54 47 PM" src="https://user-images.githubusercontent.com/58783823/114551697-612d3900-9c81-11eb-8fba-d036b4e4bf55.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env

![image](https://user-images.githubusercontent.com/55895538/115651286-d5dd3300-a365-11eb-8088-dba3a24f93c4.png)
