### ISSUE TITLE
Update feedback link on the welcome banner to point to Github template

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/micro-frontends-earn-app#95]

**Comment by SathyaJayabal** [comment]
verified
<img width="1431" alt="Screenshot 2021-05-03 at 9 05 12 PM" src="https://user-images.githubusercontent.com/58783823/116898139-a4ad0e80-ac53-11eb-84dc-59bf6e81a465.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-03 at 9 29 32 PM" src="https://user-images.githubusercontent.com/58783823/116900763-bcd25d00-ac56-11eb-9232-227dbb448adf.png">
